[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:listen --timeout=0 --sleep=3 --tries=3
user=root
numprocs=5
autostart=true
autorestart=true
startreties=10
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/home/laravel-worker.log