[program:laravel-reverb]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan reverb:start --debug
user=root
numprocs=1
autostart=true
autorestart=true
stdout_logfile=/home/laravel-reverb.log