server {
    server_name _;
    root /var/www/html/public;
    index index.html index.htm index.php;
    client_max_body_size 100M;
    autoindex off;

    location / {
        try_files $uri $uri/ /index.php?$is_args$query_string;
    }

    error_page 404/ 404.html;
    error_page 500 502 503 504 /50x.html;
    
    location = /50x.html {
        root /var/www/;
    }

    location ~ \.php$ {
        fastcgi_split_path_info $(.+\php)(/.+)$;
        fastcgi_pass unix:/var/run/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_FILENAME $fastcgi_script_name;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_read_timeout 3000;
        fastcgi_param SERVER_NAME example.com;
    }

    location ~ .*\(gif|jpg|jpeg|png|bmp|swf)$ {
        expires 30d;
    }

    location ~ .*\(js|css)$ {
        expires 2h;
    }
    location ~ /.well-known {
        allow all;
    }
    location ~ /\.h {
        deny all;
    }
}