[PARSER]
    Name    nginx
    Format  regex
    Reges   ^(?<remote>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+) (?<uri>\S+) (?<protocol>\S+)" (?<status>\d+) (?<size>\d+) "(?<referer>[^"]*)" "(?<agent>[^"]*)"
    Time_key    time
    Time_format %d/%b/%Y:%H:%M:%S %z

[PARSER]
    Name    json
    Format  json